name: algo_lapcp
description: ALGO/LAPCP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
